---
# - hosts: esxi
#   gather_facts: no
#   roles:
#     - role: esxiGuestShutdown
#     - role: esxiHostShutdown
- hosts: freenas
  gather_facts: no
  remote_user: root
  roles:
    - role: freenasShutdown
