- name: Get Basic Auth string
  delegate_to: localhost
  script: encode_auth.py -u root -p {{ ansible_ssh_pass }}
  register: basic_auth_string

- name: Shutdown Freenas API
  delegate_to: localhost
  uri:
    url: "https://{{ freenas_addr }}/api/v1.0/system/shutdown/"
    method: POST
    validate_certs: no
    headers: 
      Content-Type: "application/json"
      Authorization: "{{ basic_auth_string }}"
  register: free_api

- name: debug freenas data
  debug:
    msg: "{{ free_api }}"

- name: Wait for ssh to be down
  connection: local
  wait_for:
    port: 22
    search_regex: OpenSSH
    host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
    delay: 10
    state: stopped
    timeout: 600
