- name: Shutdown Freenas API
  delegate_to: localhost
  uri:
    url: "http://{{ inventory_hostname }}/api/v1.0/system/shutdown/"
    method: POST
    validate_certs: no
    url_username: 'root'
    url_password: "{{ ansible_ssh_pass }}"
    force_basic_auth: yes
    status_code:
        - 200
        - 202
    headers: 
      Content-Type: "application/json"
  register: free_api

- name: debug freenas data
  debug:
    msg: "{{ free_api }}"

- name: Wait for ssh to be down
  connection: local
  wait_for:
    port: 22
    search_regex: OpenSSH
    host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
    delay: 10
    state: stopped
    timeout: 600
