- name: Shutdown freenas
  tags:
    - lab_off
  shell: poweroff +30s
  register: pout

- name: debug freenas data
  tags:
    - lab_off
  debug:
    msg: "{{ pout }}"

- name: Wait for ssh to be down
  tags:
    - lab_off
  delegate_to: localhost
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    delay: 10
    state: stopped
    timeout: 600
