- name: PowerOff ESXI
  tags:
    - lab_off
  vmware_host_powerstate:
    hostname: "{{ esxi_node }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_password }}"
    validate_certs: no
    esxi_hostname: "{{ esxi_node }}"
    state: shutdown-host
    force: yes
  delegate_to: localhost
  register: esxi_power

- name: Wait for ssh to be down
  tags:
    - lab_off
  connection: local
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    delay: 10
    state: stopped
    timeout: 600
