- name: PowerOff ESXI
  vmware_host_powerstate:
    hostname: "{{ esxi_node }}"
    username: "{{ esxi_user }}"
    password: "{{ esxi_password }}"
    validate_certs: no
    esxi_hostname: "{{ esxi_node }}"
    state: shutdown-host
    force: yes
  delegate_to: localhost
  register: esxi_power
  
- name: debug esxi facts
  debug:
    var: "{{ esxi_power }} "
