- name: Shutdown linux host
  shell: "sleep 10 && shutdown"
  
- name: Wait for ssh to be down
  connection: local
  wait_for:
    port: 22
    search_regex: OpenSSH
    host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
    delay: 10
    state: stopped
    timeout: 600
