- name: Shutdown linux host
  tags:
    - lab_off
  shell: shutdown +1
  
- name: Wait for ssh to be down
  tags:
    - lab_off
  delegate_to: localhost
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    delay: 10
    state: stopped
    timeout: 600
