# - name: Turn off monitor plug
#   delegate_to: localhost
#   kasa_smartstrip_powerstate:
#     ss_plug: kasa-ss-2
#     plug_index: 5
#     powerstate: absent
- name: Get plug info
  delegate_to: localhost
  kasa_smartstrip_getplugs:
    ss_plug: kasa-ss-2
  register: kasaInfo
- name: debug
  debug:
    msg: "{{ kasaInfo }}"
