- name: Get plug info
  delegate_to: localhost
  kasa_smartstrip_getplugs:
    ss_plug: "{{ item }}"
    name: 'monitor'
  register: kasaInfo
  loop:
    - kasa-ss-1
    - kasa-ss-2
- name: Turn off monitor plug
  delegate_to: localhost
  kasa_smartstrip_powerstate:
    ss_plug: "{{ item.1.host }}"
    plug_index: "{{ item.1.index }}"
    powerstate: present
  loop: "{{ kasaInfo.results | subelements('plugs', skip_missing=True) }}"
