- name: Get plug info
  delegate_to: localhost
  kasa_smartstrip_getplugs:
    ss_plug: "{{ item }}"
    name: monitor
  register: kasaInfo
  loop: "{{ smart_strips }}"

- name: Turn off all plugs
  delegate_to: localhost
  tags:
    - poff
  kasa_smartstrip_powerstate:
    ss_plug: "{{ item.1.host }}"
    plug_index: "{{ item.1.index }}"
    powerstate: absent
  loop: "{{ kasaInfo.results | subelements('plugs', skip_missing=True) }}"

- name: Turn off all plugs
  delegate_to: localhost
  tags:
    - pon
  kasa_smartstrip_powerstate:
    ss_plug: "{{ item.1.host }}"
    plug_index: "{{ item.1.index }}"
    powerstate: present
  loop: "{{ kasaInfo.results | subelements('plugs', skip_missing=True) }}"
  