- name: Get plug info
  delegate_to: localhost
  kasa_smartstrip_getplugs:
    ss_plug: "{{ item }}"
    name: '7280'
  register: kasaInfo
  loop:
    - kasa-ss-1
    - kasa-ss-2
- name: set plugs facts
  var:
    kasa_plugs: []
  set_fact:
    kasa_plugs: "{{ kasa_plugs + [ item.plugs ] }}"
  loop: "{{ kasaInfo.results }}"
- name: debug
  debug:
    msg: "{{ item }}"
  loop: "{{ kasa_plugs }}"
# - name: Turn off monitor plug
#   delegate_to: localhost
#   kasa_smartstrip_powerstate:
#     ss_plug: "{{ item.plugs.host }}"
#     plug_index: 5
#     powerstate: absent
#   loop: "{{ kasaInfo.results }}"
