- name: Get plug info
  delegate_to: localhost
  kasa_smartstrip_getplugs:
    ss_plug: "{{ item }}"
  register: kasaInfo
  loop:
    - kasa-ss-1
    - kasa-ss-2
- name: debug
  debug:
    msg: "{{ item }}"
  loop: "{{ kasaInfo.ansible_module_results }}"
# - name: Turn off monitor plug
#   delegate_to: localhost
#   kasa_smartstrip_powerstate:
#     ss_plug: kasa-ss-2
#     plug_index: 5
#     powerstate: absent
